"""Managed Mosquitto backend broker server."""

from __future__ import annotations

import asyncio
import logging
from pathlib import Path
import shutil
import socket
import subprocess
import threading

_READY_TIMEOUT_SECONDS = 5.0
_SHUTDOWN_TIMEOUT_SECONDS = 5.0


def build_broker_config(port: int) -> str:
    """Return a Mosquitto config for the local plaintext backend listener."""
    return "\n".join(
        [
            "# Generated by roborock_local_server",
            f"listener {port}",
            "allow_anonymous true",
            "connection_messages true",
            "log_dest stdout",
            "log_type error",
            "log_type warning",
            "log_type notice",
            "log_type information",
            "persistence false",
            "# Mosquitto accepts MQTT v3.1.1 and v5 clients on the same listener.",
            "",
        ]
    )


def resolve_mosquitto_binary(mosquitto_binary: str = "mosquitto") -> str:
    """Resolve the Mosquitto executable from PATH or an explicit file path."""
    resolved = shutil.which(mosquitto_binary)
    if resolved:
        return resolved
    candidate = Path(mosquitto_binary)
    if candidate.exists():
        return str(candidate.resolve())
    raise FileNotFoundError(
        "Mosquitto executable not found. Install Mosquitto or set broker.mosquitto_binary."
    )


class MosquittoBroker:
    """Own the Mosquitto subprocess used as the backend plaintext broker."""

    backend_name = "mosquitto"

    def __init__(
        self,
        *,
        port: int,
        state_dir: Path,
        mosquitto_binary: str = "mosquitto",
        logger: logging.Logger | None = None,
    ) -> None:
        self.port = port
        self.state_dir = Path(state_dir)
        self.mosquitto_binary = mosquitto_binary
        self.logger = logger or logging.getLogger(__name__)
        self.config_path = self.state_dir / "mosquitto.conf"
        self._process: subprocess.Popen[str] | None = None
        self._stdout_thread: threading.Thread | None = None
        self._resolved_binary: str | None = None

    def _write_config(self) -> None:
        self.state_dir.mkdir(parents=True, exist_ok=True)
        self.config_path.write_text(build_broker_config(self.port), encoding="utf-8")

    def _pump_stdout(self) -> None:
        process = self._process
        if process is None or process.stdout is None:
            return
        for line in process.stdout:
            message = line.rstrip()
            if message:
                self.logger.info("[mosquitto] %s", message)

    def _start_stdout_pump(self) -> None:
        if self._process is None or self._process.stdout is None:
            return
        self._stdout_thread = threading.Thread(
            target=self._pump_stdout,
            daemon=True,
            name="mosquitto-stdout",
        )
        self._stdout_thread.start()

    @staticmethod
    def _is_port_open(host: str, port: int) -> bool:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.settimeout(0.2)
            return sock.connect_ex((host, port)) == 0

    async def start(self) -> MosquittoBroker:
        self._resolved_binary = resolve_mosquitto_binary(self.mosquitto_binary)
        self._write_config()
        self._process = subprocess.Popen(
            [self._resolved_binary, "-c", str(self.config_path)],
            cwd=str(self.state_dir),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
            text=True,
            bufsize=1,
        )
        self._start_stdout_pump()
        await self._wait_until_ready()
        self.logger.info(
            "Mosquitto ready on 0.0.0.0:%d using %s",
            self.port,
            self._resolved_binary,
        )
        return self

    async def _wait_until_ready(self) -> None:
        loop = asyncio.get_running_loop()
        deadline = loop.time() + _READY_TIMEOUT_SECONDS
        while True:
            process = self._process
            if process is None:
                raise RuntimeError("Mosquitto process was not started")
            exit_code = process.poll()
            if exit_code is not None:
                raise RuntimeError(
                    f"Mosquitto exited before becoming ready (exit_code={exit_code}). "
                    f"Check {self.config_path} and mqtt_server.log."
                )
            if self._is_port_open("127.0.0.1", self.port):
                return
            if loop.time() >= deadline:
                raise RuntimeError(
                    f"Mosquitto did not open 127.0.0.1:{self.port} within "
                    f"{_READY_TIMEOUT_SECONDS:.1f}s."
                )
            await asyncio.sleep(0.1)

    async def shutdown(self) -> None:
        process = self._process
        self._process = None
        if process is None:
            return
        if process.poll() is None:
            self.logger.info("Stopping Mosquitto broker (pid=%s)", process.pid)
            process.terminate()
            try:
                await asyncio.to_thread(process.wait, _SHUTDOWN_TIMEOUT_SECONDS)
            except subprocess.TimeoutExpired:
                self.logger.warning("Mosquitto did not stop cleanly; killing pid=%s", process.pid)
                process.kill()
                await asyncio.to_thread(process.wait, _SHUTDOWN_TIMEOUT_SECONDS)
        self.logger.info("Mosquitto broker stopped")


async def start_broker(
    port: int,
    *,
    state_dir: Path,
    mosquitto_binary: str = "mosquitto",
    logger: logging.Logger | None = None,
) -> MosquittoBroker:
    broker = MosquittoBroker(
        port=port,
        state_dir=state_dir,
        mosquitto_binary=mosquitto_binary,
        logger=logger,
    )
    await broker.start()
    return broker
